#ifndef PPG_IBI_CONFIG_H
#define PPG_IBI_CONFIG_H

#include "ppg_ibi.h"

#define PPG_IBI_DEFAULT_MIN_IBI_MS (300u)
#define PPG_IBI_DEFAULT_MAX_IBI_MS (2000u)
#define PPG_IBI_DEFAULT_TIMESTAMP_TOLERANCE_MS (20u)
#define PPG_IBI_DEFAULT_SAMPLE_COUNT_TOLERANCE (1u)

#endif /* PPG_IBI_CONFIG_H */
